site_name: Teacher Pedro
site_url: https://www.phsg.com.br
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - mkdocs-video:
      enabled: true
  - blog:
      enabled: false
  
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - English Language 3:
    - Home: eng3/index.md
    - Syllabus: eng3/syllabus.md
    - Materials: eng3/materials.md
    - Assignments: eng3/assignments.md
  - English Literature 1:
    - Home: lit1/index.md
    - Syllabus: lit1/syllabus.md
    - Materials: lit1/materials.md
    - Assignments: lit1/assignments.md
  - English Literature 5:
    - Home: lit5/index.md
    - Syllabus: lit5/syllabus.md
    - Materials: lit5/materials.md
    - Assignments: lit5/assignments.md